spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
  cloud.stream:
    bindings.output:
      destination: payment-service-pipe
      contentType: application/json
server:
  port: ${SERVER_PORT:8080}