spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud.stream:
    bindings:
      input:
        destination: credit-service-pipe
        group: credit-service