spring:
  main:
    web-application-type: none
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
  cloud.stream:
    rabbit:
      bindings:
        input:
          consumer:
            auto-bind-dlq: true
            republish-to-dlq: true
    bindings:
      input:
        destination: payment-service-pipe
        group: payment-service
      output:
        destination: restaurant-service-pipe
        contentType: application/json
