version: "3.7"

services: 
  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports: 
      - 15672:15672
      - 5672:5672
    restart: on-failure
  mongo:
    container_name: mongo
    image: mongo
    restart: on-failure
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: on-failure

networks:
  default:
    name: skynet
volumes:
  db: