version: "3.7"

services: 
  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 15672:15672
      - 5672:5672
    restart: on-failure
    networks: 
      - skynet
  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: on-failure

networks: 
  skynet:
volumes:
  db: