version: "3.7"

services:
  orders-api:
    build:
      context: ../orders-api
    environment:
      - RABBIT_HOST=rabbit
    ports:
      - 8080:8080
  payment-service:
    build:
      context: ../payment-service
    environment:
      - RABBIT_HOST=rabbit
      - REDIS_HOST=redis
  restaurant-service:
    build:
      context: ../restaurant-service
    environment:
      - RABBIT_HOST=rabbit
      - ELS_CLUSTER_NODES=elasticsearch:9300
      - ELS_CLUSTER_NAME=single-cluster

networks:
  default:
    name: skynet