spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
  cloud.stream:
    bindings:
      input:
        destination: credit-service-pipe
        group: credit-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
server:
  port: ${SERVER_PORT:9090}