spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
  cloud.stream:
    bindings:
      input:
        destination: restaurant-service-pipe
        group: restaurant-service
        consumer:
          auto-bind-dlq: true
          republish-to-dlq: true
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: ${ELS_CLUSTER_NODES:localhost:9300}
      cluster-name: ${ELS_CLUSTER_NAME:elasticsearch}
  server:
    port: ${SERVER_PORT:9090}
#elasticsearch:
#  host: ${ELS_HOST:localhost}
#  port: ${ELS_PORT:9300}

